// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnHFSAn3Nh7GfZQNE9wYNAt-IV6OUkDc',
    appId: '1:203101911094:android:d4d5f5be25cf0e07478097',
    messagingSenderId: '203101911094',
    projectId: 'coremicron-9f1a1',
    storageBucket: 'coremicron-9f1a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKOwINS4TG2tcOqViCocHaEIF7249LYE',
    appId: '1:203101911094:ios:5bd7fa18d82380f2478097',
    messagingSenderId: '203101911094',
    projectId: 'coremicron-9f1a1',
    storageBucket: 'coremicron-9f1a1.appspot.com',
    iosBundleId: 'com.example.coremicron',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKOwINS4TG2tcOqViCocHaEIF7249LYE',
    appId: '1:203101911094:ios:5bd7fa18d82380f2478097',
    messagingSenderId: '203101911094',
    projectId: 'coremicron-9f1a1',
    storageBucket: 'coremicron-9f1a1.appspot.com',
    iosBundleId: 'com.example.coremicron',
  );
}
